from __future__ import annotations

from typing import Iterable

from sqlalchemy.orm import Session

from app.models.schema import LocalizationEntry

SUPPORTED_LANGUAGES = ("ru", "uz", "en")


def loc(ru: str, uz: str, en: str) -> dict[str, str]:
    return {"ru": ru, "uz": uz, "en": en}


CATALOG: dict[str, dict[str, dict[str, str]]] = {
    "reminder": {
        "daily_nudge": loc(
            "Сегодняшний корейский: 5 минут урока или повторения?",
            "Bugungi koreys tili: 5 daqiqa dars yoki takrorlash?",
            "Today's Korean: 5 minutes for a lesson or review?",
        ),
    },
    "web": {
        "app.title": loc("Korean Learn", "Korean Learn", "Korean Learn"),
        "loading.session": loc("Загружаю сессию Telegram…", "Telegram sessiyasi yuklanmoqda…", "Loading Telegram session..."),
        "error.init_session": loc("Не удалось открыть сессию Telegram.", "Telegram sessiyasini ishga tushirib bo'lmadi.", "Could not initialize Telegram session."),
        "action.retry": loc("Повторить", "Qayta urinish", "Retry"),
        "action.back_home": loc("Назад домой", "Bosh sahifaga qaytish", "Back home"),
        "action.next": loc("Дальше", "Keyingi", "Next"),
        "action.previous": loc("Назад", "Oldingi", "Previous"),
        "action.continue": loc("Продолжить", "Davom etish", "Continue"),
        "action.save": loc("Сохранить", "Saqlash", "Save"),
        "action.saved": loc("Сохранено", "Saqlandi", "Saved"),
        "action.open": loc("Открыть", "Ochish", "Open"),
        "route.home": loc("Главная", "Bosh sahifa", "Home"),
        "route.lesson": loc("Урок", "Dars", "Lesson"),
        "route.review": loc("Повторение", "Takrorlash", "Review"),
        "route.scenarios": loc("Сценарии", "Vaziyatlar", "Scenarios"),
        "route.vocab": loc("Слова", "So'zlar", "Vocabulary"),
        "route.grammar": loc("Грамматика", "Grammatika", "Grammar"),
        "route.progress": loc("Прогресс", "Progress", "Progress"),
        "route.settings": loc("Настройки", "Sozlamalar", "Settings"),
        "route.admin": loc("Админ", "Admin", "Admin"),
        "subtitle.home": loc("Серьёзное изучение корейского в ритме Telegram", "Telegram ritmida jiddiy koreys tili o'rganish", "Serious mobile Korean learning"),
        "subtitle.lesson": loc("Пошаговый урок", "Bosqichma-bosqich dars", "Step-based guided lesson"),
        "subtitle.review": loc("Центр повторения", "Takrorlash markazi", "Review center"),
        "subtitle.scenarios": loc("Практика живых диалогов", "Haqiqiy dialoglar mashqi", "Real-life dialogue practice"),
        "subtitle.vocab": loc("Слова и сигналы повторения", "So'zlar va takrorlash signallari", "Word bank and review cues"),
        "subtitle.grammar": loc("Шаблоны, заметки и ошибки", "Andozalar, izohlar va xatolar", "Patterns, notes, and mistakes"),
        "subtitle.progress": loc("Ритм недели и слабые места", "Haftalik ritm va zaif joylar", "Weekly rhythm and weak areas"),
        "subtitle.settings": loc("Telegram-настройки", "Telegram sozlamalari", "Telegram-native preferences"),
        "subtitle.admin": loc("Контент и публикация", "Kontent va nashr", "Content operations"),
        "shell.settings": loc("Настройки", "Sozlamalar", "Settings"),
        "topic.all": loc("Все", "Barchasi", "All"),
        "topic.daily_life": loc("Повседневное", "Kundalik", "Daily life"),
        "topic.food": loc("Еда", "Ovqat", "Food"),
        "topic.shopping": loc("Покупки", "Xarid", "Shopping"),
        "topic.transport": loc("Транспорт", "Transport", "Transport"),
        "topic.study": loc("Учёба", "O'qish", "Study"),
        "topic.work": loc("Работа", "Ish", "Work"),
        "topic.health": loc("Здоровье", "Salomatlik", "Health"),
        "topic.grammar": loc("Грамматика", "Grammatika", "Grammar"),
        "topic.vocabulary": loc("Слова", "So'zlar", "Vocabulary"),
        "topic.general": loc("Общее", "Umumiy", "General"),
        "state.error_title": loc("Что-то пошло не так", "Nimadir noto'g'ri ketdi", "Something went wrong"),
        "state.loading": loc("Загрузка", "Yuklanmoqda", "Loading"),
        "audio.play": loc("Слушать", "Tinglash", "Play"),
        "audio.pause": loc("Пауза", "Pauza", "Pause"),
        "audio.replay": loc("Сначала", "Qayta", "Replay"),
        "audio.loading": loc("Загрузка…", "Yuklanmoqda…", "Loading..."),
        "audio.unsupported": loc("Ваш браузер не поддерживает воспроизведение аудио.", "Brauzeringiz audio ijroni qo'llab-quvvatlamaydi.", "Your browser does not support audio playback."),
        "audio.unavailable": loc("Аудио сейчас недоступно.", "Audio hozircha mavjud emas.", "Audio is unavailable right now."),
        "audio.blocked": loc("Воспроизведение заблокировано.", "Ijro bloklandi.", "Playback was blocked."),
        "audio.seek": loc("Перемотка аудио", "Audio bo'ylab yurish", "Seek audio"),
        "audio.transcript.hide": loc("Скрыть текст", "Matnni yashirish", "Hide transcript"),
        "audio.transcript.reveal": loc("Показать текст", "Matnni ko'rsatish", "Reveal transcript"),
        "audio.transcript.locked": loc("Текст откроется после завершения", "Matn tugagach ochiladi", "Transcript unlocks after completion"),
        "difficulty.a0": loc("A0 старт", "A0 boshlanish", "A0 starter"),
        "difficulty.a1": loc("A1 база", "A1 baza", "A1 foundation"),
        "difficulty.a2": loc("A2 рост", "A2 o'sish", "A2 stretch"),
        "difficulty.b1": loc("B1 практика", "B1 amaliyot", "B1 applied"),
        "difficulty.b2": loc("B2 продвинутый", "B2 yuqori", "B2 advanced"),
        "difficulty.mixed": loc("Смешанный уровень", "Aralash daraja", "Mixed level"),
        "onboarding.brand_subtitle": loc(
            "Одна бесплатная направляемая программа корейского в коротких Telegram-сессиях.",
            "Telegram uchun qisqa sessiyalardagi bitta bepul boshqariladigan koreys kursi.",
            "One free guided Korean curriculum in Telegram-sized sessions.",
        ),
        "onboarding.interface_language": loc("Язык интерфейса", "Interfeys tili", "Interface language"),
        "onboarding.explanation_language": loc("Язык объяснений", "Izoh tili", "Explanation language"),
        "onboarding.level": loc("Стартовый уровень", "Boshlang'ich daraja", "Level"),
        "onboarding.daily_time": loc("Время в день", "Kunlik vaqt", "Daily time"),
        "onboarding.learning_style": loc("Стиль обучения", "O'rganish usuli", "Learning style"),
        "onboarding.save_error": loc("Не удалось сохранить параметры старта.", "Boshlang'ich sozlamalarni saqlab bo'lmadi.", "Could not save your onboarding choices."),
        "onboarding.start": loc("Начать курс", "Kursni boshlash", "Start curriculum"),
        "language.ru": loc("Русский", "Ruscha", "Russian"),
        "language.uz": loc("Узбекский", "O'zbekcha", "Uzbek"),
        "language.en": loc("Английский", "Inglizcha", "English"),
        "level.complete_beginner": loc("С нуля", "Noldan", "Complete beginner"),
        "level.knows_hangul": loc("Знаю хангыль", "Hangulni bilaman", "Knows Hangul"),
        "level.knows_basics": loc("Знаю основы", "Asoslarni bilaman", "Knows basics"),
        "time.5": loc("5 мин", "5 daqiqa", "5 min"),
        "time.10": loc("10 мин", "10 daqiqa", "10 min"),
        "time.20": loc("20 мин", "20 daqiqa", "20 min"),
        "time.30": loc("30 мин", "30 daqiqa", "30 min"),
        "style.mixed": loc("Смешанный", "Aralash", "Mixed"),
        "style.grammar_first": loc("Сначала грамматика", "Avval grammatika", "Grammar first"),
        "style.phrase_first": loc("Сначала фразы", "Avval iboralar", "Phrase first"),
        "home.today": loc("Сегодня", "Bugun", "Today"),
        "home.load_error": loc("Не удалось загрузить главную панель.", "Bosh sahifani yuklab bo'lmadi.", "Could not load your dashboard."),
        "home.no_data_title": loc("Пока нет данных об учёбе", "Hali o'qish ma'lumoti yo'q", "No study data yet"),
        "home.no_data_description": loc(
            "Начните первый урок, и эта главная страница станет вашим ежедневным пультом.",
            "Birinchi darsni boshlang, shunda bu bosh sahifa kunlik boshqaruv paneliga aylanadi.",
            "Start your first lesson and this dashboard will turn into your daily control panel.",
        ),
        "home.start_lesson": loc("Начать урок", "Darsni boshlash", "Start lesson"),
        "home.keep_close_title": loc("Держите приложение в одном касании", "Ilovani bir tegishda ushlang", "Keep the app one tap away"),
        "home.keep_close_description": loc(
            "Добавьте Korean Learn на главный экран, если заходите каждый день.",
            "Har kuni ishlatsangiz, Korean Learn'ni bosh ekranga qo'shing.",
            "Add Korean Learn to your home screen if you use it daily.",
        ),
        "home.add_to_home": loc("Добавить на экран", "Bosh ekranga qo'shish", "Add to home screen"),
        "home.not_now": loc("Не сейчас", "Hozir emas", "Not now"),
        "home.current_lesson": loc("Текущий урок", "Joriy dars", "Current lesson"),
        "home.no_lesson_active": loc("Сейчас нет активного урока", "Hozir faol dars yo'q", "No lesson active"),
        "home.lessons_complete": loc("уроков пройдено", "ta dars tugallangan", "lessons complete"),
        "home.continue_lesson": loc("Продолжить урок", "Darsni davom ettirish", "Continue lesson"),
        "home.two_minute_review": loc("2-минутный повтор", "2 daqiqalik takror", "2-minute review"),
        "home.xp": loc("XP", "XP", "XP"),
        "home.xp_detail": loc("Все очки", "Jami ball", "All-time study points"),
        "home.streak": loc("Серия", "Ketma-ketlik", "Streak"),
        "home.streak_next": loc("Следующая цель {count}", "Keyingi marrа {count}", "Next {count}"),
        "home.due_reviews": loc("Повторение к сроку", "Navbatdagi takror", "Due reviews"),
        "home.ready_now": loc("Можно сейчас", "Hozir tayyor", "Ready now"),
        "home.completed": loc("Завершено", "Tugallangan", "Completed"),
        "home.completed_detail": loc("Пройденные уроки", "Tugagan darslar", "Lessons finished"),
        "home.review_now": loc("Повторить сейчас", "Hozir takrorlash", "Review now"),
        "home.attention_first": loc("Что требует внимания первым", "Avval nimaga e'tibor kerak", "What needs attention first"),
        "home.review_due_title": loc("Повторение по сроку", "Navbatdagi takror", "Due review"),
        "home.review_due_open": loc("Открыть повтор", "Takrorni ochish", "Open review"),
        "home.mistakes_title": loc("Разбор ошибок", "Xatolarni tuzatish", "Mistakes review"),
        "home.focus_mistakes": loc("Разобрать ошибки", "Xatolarga e'tibor", "Focus mistakes"),
        "home.no_mistake_queue": loc("Очередь ошибок сейчас пуста.", "Xatolar navbati hozir bo'sh.", "No open mistake queue right now."),
        "home.recommended": loc("Рекомендуется", "Tavsiya", "Recommended"),
        "home.continue": loc("Продолжить", "Davom etish", "Continue"),
        "home.open_scenario": loc("Открыть сценарий", "Ssenariyni ochish", "Open scenario"),
        "home.progress_snapshot": loc("Снимок прогресса", "Progress ko'rinishi", "Progress snapshot"),
        "home.recent_progress": loc("Недавний прогресс", "So'nggi progress", "Recent progress"),
        "home.last_completed_lesson": loc("Последний завершённый урок", "Oxirgi tugallangan dars", "Last completed lesson"),
        "home.no_completed_lesson": loc("Вы ещё не завершили урок.", "Hali hech bir dars tugamagan.", "You have not completed a lesson yet."),
        "home.weak_areas": loc("Слабые места", "Zaif joylar", "Weak areas"),
        "home.no_weak_spots": loc("Повторяющихся слабых мест пока нет.", "Hali takroriy zaif joylar yo'q.", "No recurring weak spots yet."),
        "home.weekly_habit": loc("Ритм недели", "Haftalik odat", "Weekly habit"),
        "home.keep_cadence": loc("Держите ритм маленьким", "Ritmni kichik ushlang", "Keep the cadence small"),
        "home.on": loc("Да", "Bor", "On"),
        "home.off": loc("Нет", "Yo'q", "Off"),
        "home.current_streak": loc("Текущая серия", "Joriy ketma-ketlik", "Current streak"),
        "home.days": loc("дней", "kun", "days"),
        "home.open_progress": loc("Открыть прогресс", "Progressni ochish", "Open progress"),
        "home.quick_jump": loc("Быстрый переход", "Tez o'tish", "Quick jump"),
        "home.choose_lane": loc("Выберите формат учёбы", "O'qish yo'nalishini tanlang", "Choose a study lane"),
        "home.open_vocab": loc("Открыть слова", "So'zlarni ochish", "Open vocab"),
        "home.open_grammar": loc("Открыть грамматику", "Grammatikani ochish", "Open grammar"),
        "home.open_scenarios": loc("Открыть сценарии", "Ssenariylarni ochish", "Open scenarios"),
        "review.session_complete": loc("Сессия завершена", "Sessiya tugadi", "Session complete"),
        "review.load_error": loc("Не удалось загрузить материалы для повторения.", "Takror materiallarini yuklab bo'lmadi.", "Could not load review content."),
        "review.finished": loc("{title} завершён", "{title} tugadi", "{title} finished"),
        "review.completed_summary": loc("Вы прошли {count} заданий с точностью {accuracy}%.", "{count} ta topshiriqni {accuracy}% aniqlik bilan bajardingiz.", "You completed {count} prompts with {accuracy}% accuracy."),
        "review.correct": loc("Верно", "To'g'ri", "Correct"),
        "review.accuracy": loc("Точность", "Aniqlik", "Accuracy"),
        "review.repeat_session": loc("Повторить сессию", "Sessiyani takrorlash", "Repeat session"),
        "review.center": loc("Центр повторения", "Takrorlash markazi", "Review center"),
        "review.session_size": loc("Размер сессии", "Sessiya hajmi", "Session size"),
        "review.choose_length": loc("Выберите длину сессии", "Sessiya uzunligini tanlang", "Choose the session length"),
        "review.items": loc("элементов", "ta element", "items"),
        "review.signals": loc("Сигналы", "Signallar", "Signals"),
        "review.clustering": loc("Где скапливаются ошибки", "Xatolar qayerda to'planmoqda", "Where mistakes are clustering"),
        "review.weak_grammar": loc("Слабая грамматика", "Zaif grammatika", "Weak grammar"),
        "review.no_grammar_cluster": loc("Кластера грамматики пока нет.", "Hali grammatika klasteri yo'q.", "No grammar cluster yet."),
        "review.repeated_mistakes": loc("Повторяющиеся ошибки", "Takroriy xatolar", "Repeated mistakes"),
        "review.no_repeated": loc("Повторяющихся ошибок сейчас нет.", "Hozir takroriy xato yo'q.", "No repeated misses right now."),
        "review.by_type": loc("По типу упражнений", "Mashq turi bo'yicha", "By exercise type"),
        "review.no_breakdown": loc("Разбивки по типам пока нет.", "Hali tur bo'yicha taqsimot yo'q.", "No type breakdown yet."),
        "review.empty_title": loc("В этой очереди пусто", "Bu navbat bo'sh", "Nothing in this queue"),
        "review.review_item": loc("Повтор {current}/{total}", "{current}/{total} takror", "Review {current}/{total}"),
        "review.mistakes_count": loc("{count} ошибок", "{count} xato", "{count} mistakes"),
        "review.still_shaky": loc("Пока шатко", "Hali mustahkam emas", "Still shaky"),
        "review.solid_now": loc("Уже уверенно", "Endi aniq", "Solid now"),
        "review.active_review": loc("Активное повторение", "Faol takror", "Active review"),
        "review.next_item": loc("Следующий", "Keyingi", "Next item"),
        "review.try_again": loc("Попробовать снова", "Yana urinib ko'rish", "Try again"),
        "lesson.guided": loc("Направляемый урок", "Boshqariladigan dars", "Guided lesson"),
        "lesson.loading": loc("Загрузка урока", "Dars yuklanmoqda", "Loading lesson"),
        "lesson.load_error": loc("Не удалось загрузить урок.", "Darsni yuklab bo'lmadi.", "Could not load your lesson."),
        "lesson.no_active_title": loc("Нет активного урока", "Faol dars yo'q", "No active lesson"),
        "lesson.no_active_description": loc(
            "Следующий направляемый урок появится здесь, как только откроется.",
            "Keyingi boshqariladigan dars shu yerda ochiladi.",
            "The next guided lesson will appear here as soon as it is unlocked.",
        ),
        "lesson.listen": loc("Слушать", "Tinglash", "Listen"),
        "lesson.lesson_audio": loc("Аудио урока", "Dars audio", "Lesson audio"),
        "lesson.lesson_audio_description": loc(
            "Послушайте аудио до ответа, чтобы настроить слух на шаблон.",
            "Javob berishdan oldin audioga quloq tuting.",
            "Use the audio before you answer to tune your ear to the target pattern.",
        ),
        "lesson.premium": loc("Премиум", "Premium", "Premium"),
        "lesson.listening_locked": loc("Аудио закрыто", "Audio yopiq", "Listening is locked"),
        "lesson.listening_locked_description": loc(
            "В этом уроке есть премиум-аудио. Оформите доступ, чтобы включить воспроизведение и текст.",
            "Bu darsda premium audio bor. Ijro va matn uchun premium kerak.",
            "This lesson includes premium-only audio. Upgrade to unlock playback and transcript controls.",
        ),
        "lesson.audio_issue": loc("Проблема с аудио", "Audio muammosi", "Audio issue"),
        "lesson.audio_issue_description": loc(
            "Часть аудио недоступна. Остальная часть урока продолжит работать.",
            "Audio qismlaridan biri vaqtincha mavjud emas. Qolgan dars ishlaydi.",
            "Some lesson audio is unavailable. The rest of the lesson will keep working.",
        ),
        "lesson.audio_prompt": loc("Аудиоподсказка", "Audio signal", "Audio prompt"),
        "lesson.open_related_scenario": loc("Открыть связанный сценарий", "Bog'liq ssenariyni ochish", "Open related scenario"),
        "lesson.listen_first": loc("Сначала послушайте", "Avval tinglang", "Listen first"),
        "lesson.audio_cue": loc("Аудиоподсказка", "Audio signal", "Audio cue"),
        "lesson.audio_cue_description": loc(
            "Переслушайте подсказку перед ответом, если хотите сначала понять на слух.",
            "Avval eshitib yechmoqchi bo'lsangiz, audiotni qayta qo'ying.",
            "Replay the prompt before answering if you want a listening-first pass.",
        ),
        "lesson.prompt_locked": loc("Аудиоподсказка закрыта", "Audio signal yopiq", "Listening prompt locked"),
        "lesson.prompt_locked_description": loc("Оформите премиум, чтобы открыть это аудио-упражнение.", "Bu audio mashq uchun premium kerak.", "Upgrade to unlock this listening exercise."),
        "lesson.prompt_unavailable": loc("Подсказка недоступна", "Signal mavjud emas", "Prompt unavailable"),
        "lesson.prompt_unavailable_description": loc(
            "Этот премиум-клип временно недоступен, но остальной урок продолжится.",
            "Bu premium audio vaqtincha yo'q, lekin dars davom etadi.",
            "This premium listening clip is temporarily unavailable, so the rest of the lesson continues without playback.",
        ),
        "lesson.see_recap": loc("К итогам", "Xulosaga o'tish", "See recap"),
        "lesson.next_step": loc("Следующий шаг", "Keyingi qadam", "Next step"),
        "lesson.complete": loc("Урок завершён", "Dars tugadi", "Lesson complete"),
        "lesson.complete_description": loc(
            "Вы завершили урок. Закрепите ключевые шаблоны, пока воспоминание свежее.",
            "Dars tugadi. Yangi andozalarni hozir mustahkamlang.",
            "You finished the lesson. Save the key patterns now while recall is fresh.",
        ),
        "lesson.recap": loc("Краткий итог", "Qisqa xulosa", "Lesson recap"),
        "lesson.learning_targets": loc("{count} целей обучения", "{count} ta o'quv maqsadi", "{count} learning targets"),
        "lesson.use_review_next": loc("Теперь лучше перейти к повторению.", "Endi takrorlashga o'ting.", "Use review next to lock them in."),
        "lesson.linked_references": loc("Связанные материалы", "Bog'liq materiallar", "Linked references"),
        "lesson.continue_connected": loc("Продолжите связанным материалом", "Bog'liq material bilan davom eting", "Continue with connected material"),
        "lesson.review_now": loc("Повторить сейчас", "Hozir takrorlash", "Review now"),
        "lesson.steps": loc("{current}/{total} шагов", "{current}/{total} qadam", "{current}/{total} steps"),
        "exercise.prompt": loc("Задание", "Mashq", "Exercise prompt"),
        "exercise.instruction.multiple_choice": loc("Выберите один ответ, который лучше всего подходит к заданию.", "Topshiriqqa eng mos bitta javobni tanlang.", "Choose the single answer that best matches the prompt."),
        "exercise.instruction.fill_blank": loc("Введите только пропущенное слово, частицу или окончание.", "Faqat tushib qolgan so'z, ko'makchi yoki qo'shimchani yozing.", "Type only the missing word, particle, or ending."),
        "exercise.instruction.sentence_reorder": loc("Соберите предложение в естественном корейском порядке и отправьте его.", "Gapni tabiiy koreys tartibida tuzing va yuboring.", "Build the sentence in natural Korean order, then submit it."),
        "exercise.instruction.match_pairs": loc("Соедините каждую часть слева с её правильной парой.", "Chap tomondagi har bir qismni to'g'ri jufti bilan moslang.", "Pair each left-side item with its correct partner."),
        "exercise.instruction.choose_particle": loc("Выберите частицу, которая подходит к роли существительного в предложении.", "Gapdagi ot roliga mos ko'makchini tanlang.", "Pick the particle that fits the noun role in the sentence."),
        "exercise.instruction.choose_verb_ending": loc("Выберите окончание, которое подходит по тону, вежливости и форме предложения.", "Ohang, xushmuomalalik va gap turiga mos qo'shimchani tanlang.", "Choose the ending that matches tone, politeness, and sentence form."),
        "exercise.instruction.translation_selection": loc("Выберите перевод, который сохраняет весь смысл, а не только одно слово.", "Faqat bitta so'zni emas, butun ma'noni saqlaydigan tarjimani tanlang.", "Choose the translation that preserves the full meaning, not just one word."),
        "exercise.instruction.dialogue_continuation": loc("Выберите реплику, которая звучит естественно в этом разговоре.", "Bu suhbatda tabiiy eshitiladigan javobni tanlang.", "Pick the reply that sounds natural in the conversation."),
        "exercise.instruction.reading_comprehension": loc("Внимательно прочитайте текст и выберите ответ, который подтверждается им.", "Matnni diqqat bilan o'qing va aynan u qo'llab-quvvatlaydigan javobni tanlang.", "Read the sentence carefully, then choose the answer supported by the text."),
        "exercise.instruction.listen_and_choose": loc("Сначала прослушайте аудио, затем выберите лучший ответ.", "Avval audioni tinglang, keyin eng yaxshi javobni tanlang.", "Play the audio cue first, then choose the best answer."),
        "exercise.instruction.true_false": loc("Решите, верно ли утверждение в текущем виде.", "Bayonot shu ko'rinishida to'g'rimi, shuni aniqlang.", "Decide whether the statement is correct as written."),
        "exercise.instruction.recap_quiz": loc("Опирайтесь на повтор урока и выберите самый сильный ответ.", "Dars yakuniga tayangan holda eng to'g'ri javobni tanlang.", "Use the lesson recap to choose the strongest answer."),
        "exercise.instruction.flashcard_review": loc("Сначала постарайтесь вспомнить ответ, затем откройте его и оцените себя честно.", "Avval javobni eslashga urinib ko'ring, keyin uni ochib o'zingizni halol baholang.", "Try to recall the answer before you reveal it, then rate yourself honestly."),
        "exercise.instruction.fallback": loc("Внимательно прочитайте задание и отправьте самый сильный вариант ответа.", "Topshiriqni diqqat bilan o'qing va imkon qadar eng yaxshi javobni yuboring.", "Read the prompt carefully and submit the strongest answer you can."),
        "exercise.answer_placeholder": loc("Введите ответ", "Javobni yozing", "Type your answer"),
        "exercise.reorder_hint": loc("Нажимайте слова ниже, чтобы собрать предложение.", "Gapni tuzish uchun quyidagi tokenlarga bosing.", "Tap tokens below to build the sentence."),
        "exercise.match_selected": loc("{value} выбрано", "{value} tanlandi", "Matched to {value}"),
        "exercise.match_hint": loc("Сначала выберите эту сторону, затем пару.", "Avval shu tomonni, keyin juftini tanlang.", "Pick this first, then choose its pair."),
        "exercise.clear": loc("Очистить", "Tozalash", "Clear"),
        "exercise.recall_first": loc("Сначала вспомните", "Avval eslang", "Recall first"),
        "exercise.answer_revealed": loc("Ответ открыт", "Javob ochildi", "Answer revealed"),
        "exercise.recall_description": loc(
            "Остановитесь и попробуйте сказать ответ до открытия.",
            "Ochilishidan oldin javobni o'zingiz aytib ko'ring.",
            "Pause and try to say it before you reveal the answer.",
        ),
        "exercise.missed": loc("Не вспомнил", "Esga tushmadi", "Missed it"),
        "exercise.knew": loc("Вспомнил", "Bildim", "Knew it"),
        "feedback.checked": loc("Ответ проверен", "Javob tekshirildi", "Answer checked"),
        "feedback.try_again": loc("Попробуйте ещё раз", "Yana urinib ko'ring", "Try again"),
        "feedback.correct": loc("Верно", "To'g'ri", "Correct"),
        "feedback.not_yet": loc("Пока не совсем", "Hali to'liq emas", "Not quite yet"),
        "feedback.expected": loc("Ожидаемый ответ", "Kutilgan javob", "Expected answer"),
        "grammar.hero_title": loc("Локализованные объяснения и типичные переносы", "Mahalliylashtirilgan izohlar va tipik transfer xatolari", "Localized explanations and common transfer mistakes"),
        "grammar.hero_description": loc(
            "Открывайте грамматику, когда нужен явный разбор, связанный сценарий и быстрый переход обратно к практике.",
            "Aniq tuzilma, bog'liq ssenariy va tezkor amaliyotga qaytish kerak bo'lsa grammatika oynasini oching.",
            "Use the grammar view when you want explicit structure, linked scenarios, and a quick route back into practice.",
        ),
        "grammar.common_mistakes": loc("Типичные ошибки", "Ko'p xatolar", "Common mistakes"),
        "grammar.transfer_notes": loc("Переход от вашего языка", "Sizning tilingizdan ko'prik", "Bridge from your learner language"),
        "grammar.examples": loc("Примеры", "Misollar", "Examples"),
        "grammar.examples_title": loc("Услышьте шаблон в работе", "Andozani amalda ko'ring", "Hear and compare the pattern in use"),
        "grammar.quick_review": loc("Быстрый повтор грамматики", "Tez grammatika takrori", "Quick grammar review"),
        "grammar.mixed_practice": loc("Смешанная практика", "Aralash mashq", "Mixed practice"),
        "grammar.filters": loc("Фильтры", "Filtrlar", "Filters"),
        "grammar.search_title": loc("Категория и поиск шаблона", "Kategoriya va qidiruv", "Category and pattern search"),
        "grammar.search_placeholder": loc("Ищите шаблон или объяснение", "Andoza yoki izoh qidiring", "Search pattern or explanation"),
        "grammar.empty_title": loc("Нет подходящих грамматических тем", "Mos grammatika topilmadi", "No matching grammar points"),
        "grammar.empty_description": loc("Попробуйте другую категорию или более широкий поиск.", "Boshqa kategoriya yoki kengroq qidiruvni sinab ko'ring.", "Try another category or a broader search."),
        "grammar.load_error": loc("Не удалось загрузить грамматику.", "Grammatikani yuklab bo'lmadi.", "Could not load grammar."),
        "vocab.hero_title": loc("Поиск по теме и давлению повторения", "Mavzu va takrorlash bosimi bo'yicha qidiruv", "Search by topic and review pressure"),
        "vocab.hero_description": loc(
            "Используйте закладки для своих трудных слов и смотрите чипы повторения, чтобы видеть, что нужно сейчас.",
            "Qiyin so'zlar uchun saqlang va ayni paytda nima kerakligini ko'rish uchun takror chiplariga qarang.",
            "Use bookmarks for your own difficult words, and use review chips to spot what is due now.",
        ),
        "vocab.load_error": loc("Не удалось загрузить словарь.", "Lug'atni yuklab bo'lmadi.", "Could not load vocabulary."),
        "vocab.bookmark": loc("Закладка", "Saqlash", "Bookmark"),
        "vocab.mark_difficult": loc("Отметить как трудное", "Qiyin deb belgilash", "Mark difficult"),
        "vocab.pronunciation": loc("Произношение", "Talaffuz", "Pronunciation"),
        "vocab.premium_pronunciation_locked": loc("Премиум-произношение закрыто для этого слова.", "Bu so'z uchun premium talaffuz yopiq.", "Premium pronunciation audio is locked for this item."),
        "vocab.examples": loc("Примеры", "Misollar", "Examples"),
        "vocab.examples_title": loc("Посмотрите слово в контексте", "So'zni kontekstda ko'ring", "See the word in context"),
        "vocab.filters": loc("Фильтры", "Filtrlar", "Filters"),
        "vocab.filters_title": loc("Тема, теги и состояние повторения", "Mavzu, teg va takror holati", "Topic, tag, review state"),
        "vocab.search_placeholder": loc("Поиск по корейскому, чтению или переводу", "Koreyscha, o'qilishi yoki tarjima bo'yicha qidiring", "Search Korean, reading, or translation"),
        "vocab.empty_title": loc("Совпадающих слов нет", "Mos so'z topilmadi", "No matching words"),
        "vocab.empty_description": loc("Попробуйте другую тему или более широкий поиск.", "Boshqa mavzu yoki kengroq qidiruvni sinab ko'ring.", "Try another topic or a broader search."),
        "vocab.audio_locked": loc("Аудио закрыто", "Audio yopiq", "Audio locked"),
        "vocab.saved": loc("Сохранено", "Saqlangan", "Saved"),
        "vocab.difficult": loc("Трудное", "Qiyin", "Difficult"),
        "scenario.hero_eyebrow": loc("Практика сценариев", "Ssenariy mashqi", "Scenario practice"),
        "scenario.hero_title": loc("Живые корейские диалоги", "Haqiqiy koreys dialoglari", "Real-life Korean dialogues"),
        "scenario.hero_description": loc(
            "Выберите ситуацию, скрывайте перевод для давления на память и переходите в режим аудио, когда оно доступно.",
            "Vaziyatni tanlang, xotira bosimi uchun tarjimani yashiring va audio bo'lsa tinglash rejimiga o'ting.",
            "Pick a context, hide translations when you want pressure, and switch to listening mode when audio is available.",
        ),
        "scenario.filters": loc("Фильтры", "Filtrlar", "Filters"),
        "scenario.filters_title": loc("Найдите нужную ситуацию", "Kerakli vaziyatni toping", "Find the right situation"),
        "scenario.search_placeholder": loc("Ищите по теме или ситуации", "Mavzu yoki vaziyat bo'yicha qidiring", "Search by topic or situation"),
        "scenario.loading": loc("Загрузка сценариев", "Ssenariylar yuklanmoqda", "Loading scenarios"),
        "scenario.load_error": loc("Не удалось загрузить сценарии.", "Ssenariylarni yuklab bo'lmadi.", "Could not load scenarios."),
        "scenario.empty_title": loc("Подходящих сценариев нет", "Mos ssenariy topilmadi", "No matching scenarios"),
        "scenario.empty_description": loc("Попробуйте более широкую тему или очистите поиск.", "Kengroq mavzuni sinab ko'ring yoki qidiruvni tozalang.", "Try a broader topic or clear the search to browse all published dialogues."),
        "scenario.continue": loc("Продолжить", "Davom etish", "Continue"),
        "scenario.saved": loc("Сохранено", "Saqlangan", "Saved"),
        "scenario.save": loc("Сохранить сценарий", "Ssenariyni saqlash", "Save scenario"),
        "scenario.share": loc("Поделиться сценарием", "Ssenariyni ulashish", "Share scenario"),
        "scenario.back": loc("Назад", "Orqaga", "Back"),
        "scenario.audio": loc("Аудио сценария", "Ssenariy audio", "Scenario audio"),
        "scenario.audio_title": loc("Сначала послушайте весь сценарий", "Avval butun ssenariyni tinglang", "Hear the full setup first"),
        "scenario.audio_description": loc("Используйте общее аудио сценария до пошагового проигрывания диалога.", "Dialog bo'ylab yurishdan oldin umumiy audio bilan boshlang.", "Use the scenario-level audio before you step through the dialogue."),
        "scenario.audio_locked_title": loc("Режим аудио закрыт", "Tinglash rejimi yopiq", "Listening mode is locked"),
        "scenario.audio_locked_description": loc("В этом сценарии есть премиум-аудио. Воспроизведение и текст открываются только с премиумом.", "Bu ssenariyda premium audio bor. Ijro va matn premium bilan ochiladi.", "This scenario includes premium-only audio. Playback and transcript reveal stay hidden until premium access is active."),
        "scenario.audio_issue_title": loc("Часть аудио недоступна", "Ba'zi audio yo'q", "Some scenario audio is unavailable"),
        "scenario.audio_issue_description": loc("Часть премиум-клипов временно недоступна, но работа с диалогом продолжится.", "Ba'zi premium audio vaqtincha mavjud emas, ammo dialog ishlaydi.", "Playback for one or more premium clips is temporarily unavailable. Dialogue study will still work."),
        "scenario.player": loc("Плеер", "Pleyer", "Player"),
        "scenario.dialogue": loc("Диалог сценария", "Ssenariy dialogi", "Scenario dialogue"),
        "scenario.show_translation": loc("Показывать перевод", "Tarjimani ko'rsatish", "Show translation"),
        "scenario.show_translation_description": loc("Скрывайте перевод, когда хотите больше давления на память.", "Xotirani kuchaytirish uchun tarjimani yashiring.", "Hide it when you want more recall pressure."),
        "scenario.listening_mode": loc("Режим аудио", "Tinglash rejimi", "Listening mode"),
        "scenario.listening_mode_description": loc("Сначала звук, если у строк есть запись.", "Qatorlarda audio bo'lsa, avval ovozga e'tibor bering.", "Focus on audio-first playback when lines include sound."),
        "scenario.current_line": loc("Текущая строка {count}", "Joriy qator {count}", "Current line {count}"),
        "scenario.previous_line": loc("Предыдущая", "Oldingi", "Previous"),
        "scenario.next_line": loc("Следующая строка", "Keyingi qator", "Next line"),
        "scenario.complete": loc("Завершить сценарий", "Ssenariyni tugatish", "Complete scenario"),
        "scenario.useful_expressions": loc("Полезные выражения", "Foydali iboralar", "Useful expressions"),
        "scenario.useful_expressions_title": loc("Сохраните эти чанки", "Bu iboralarni olib qoling", "Keep these chunks"),
        "scenario.useful_expressions_description": loc("Эти выражения стоит унести в собственную речь.", "Bu iboralarni o'z nutqingizga olib o'ting.", "These expressions are worth stealing for your own speech."),
        "scenario.comprehension": loc("Понимание", "Tushunish", "Comprehension"),
        "scenario.comprehension_title": loc("Быстрые проверки", "Tez tekshiruvlar", "Quick checks"),
        "scenario.comprehension_description": loc("Открывайте ответ только после своей интерпретации.", "Javobni faqat avval o'zingiz yechgandan keyin oching.", "Reveal the answer only after you commit to an interpretation."),
        "scenario.related": loc("Связанные материалы", "Bog'liq material", "Related material"),
        "scenario.related_title": loc("Переход к связанным заметкам", "Bog'liq eslatmalarga o'ting", "Jump into linked study notes"),
        "scenario.related_description": loc("Открывайте слова и грамматику прямо из контекста сценария.", "Ssenariy kontekstidan to'g'ridan-to'g'ri so'z va grammatikani oching.", "Open vocabulary or grammar directly from the scenario context."),
        "scenario.done": loc("Готово", "Tayyor", "Done"),
        "scenario.done_title": loc("Сценарий завершён", "Ssenariy tugadi", "Scenario complete"),
        "scenario.done_description": loc("Пока диалог свежий, откройте связанную грамматику или слова.", "Dialog hali yodda ekan, bog'liq grammatika yoki so'zlarni oching.", "Use the related grammar or vocab next while the dialogue is still fresh."),
        "scenario.quick_review": loc("Быстрый повтор", "Tez takror", "Quick review"),
        "settings.hero_eyebrow": loc("Настройки", "Sozlamalar", "Settings"),
        "settings.hero_title": loc("Настройте продукт под себя", "Mahsulotni o'zingizga moslang", "Personalize the learning product"),
        "settings.hero_description": loc(
            "Оставляйте только те настройки, которые реально меняют ежедневное использование.",
            "Faqat kundalik foydalanishga haqiqatan ta'sir qiladigan sozlamalarni qoldiring.",
            "Keep the defaults pragmatic. Only the settings that actually change daily use are surfaced here.",
        ),
        "settings.language_eyebrow": loc("Язык", "Til", "Language"),
        "settings.language_title": loc("Язык интерфейса и объяснений", "Interfeys va izoh tili", "Interface and explanation language"),
        "settings.interface_language": loc("Язык интерфейса", "Interfeys tili", "Interface language"),
        "settings.explanation_language": loc("Язык объяснений", "Izoh tili", "Explanation language"),
        "settings.reminders_eyebrow": loc("Напоминания", "Eslatmalar", "Reminders"),
        "settings.reminders_title": loc("Напоминание об учёбе", "O'qish eslatmasi", "Study nudge"),
        "settings.reminders_description": loc("Держите напоминания простыми: вкл, время и часовой пояс.", "Eslatmalarni sodda tuting: yoqish, vaqt va vaqt zonasi.", "Keep reminders simple: on, time, timezone."),
        "settings.reminders_toggle": loc("Напоминания", "Eslatmalar", "Reminders"),
        "settings.reminders_toggle_description": loc("Telegram-подсказки для уроков и повторения.", "Dars va takror uchun Telegram eslatmalari.", "Telegram nudges for study and review."),
        "settings.reminder_time": loc("Время напоминания", "Eslatma vaqti", "Reminder time"),
        "settings.timezone": loc("Часовой пояс", "Vaqt zonasi", "Timezone"),
        "settings.learning_eyebrow": loc("Учёба", "O'qish", "Learning"),
        "settings.learning_title": loc("Сложность и стиль", "Qiyinlik va usul", "Difficulty and style"),
        "settings.learning_description": loc("Оставляйте это только если реально меняет опыт.", "Faqat tajribani o'zgartirsa qoldiring.", "Keep these only if they still change the study experience for you."),
        "settings.learning_style": loc("Стиль обучения", "O'rganish usuli", "Learning style"),
        "settings.difficulty": loc("Сложность", "Qiyinlik", "Difficulty"),
        "settings.audio_eyebrow": loc("Аудио", "Audio", "Audio"),
        "settings.audio_title": loc("Предпочтения прослушивания", "Tinglash afzalliklari", "Listening preferences"),
        "settings.audio_description": loc("Эти настройки хранятся только на этом устройстве.", "Bu sozlamalar faqat shu qurilmada saqlanadi.", "These stay local on this device unless Telegram later offers synced device storage for your setup."),
        "settings.auto_play": loc("Автовоспроизведение строк", "Qator audiolarini avtomatik qo'yish", "Auto-play line audio"),
        "settings.auto_play_description": loc("Полезно в сценариях, если у строк уже есть запись.", "Qatorlarda audio bo'lsa ssenariylarda foydali.", "Useful in scenarios when lines already have recorded audio."),
        "settings.prefer_listening": loc("Предпочитать режим аудио", "Tinglash rejimini afzal ko'rish", "Prefer listening mode"),
        "settings.prefer_listening_description": loc("Открывать строки сценария с скрытым переводом и звуком сначала.", "Ssenariy qatorlarini tarjimasiz va avval audio bilan ochish.", "Open scenario lines with translation hidden and audio first."),
        "settings.session_eyebrow": loc("Сессия", "Sessiya", "Session"),
        "settings.session_title": loc("Аккаунт и локальная видимость", "Hisob va mahalliy ko'rinish", "Account and local visibility"),
        "settings.session_description": loc("Практичная заметка о приватности вместо фальшивых переключателей.", "Soxta tugmalar o'rniga amaliy maxfiylik izohi.", "A practical privacy note instead of fake controls."),
        "settings.telegram_session": loc("Сессия Telegram", "Telegram sessiyasi", "Telegram session"),
        "settings.telegram_session_description": loc("Вы вошли как `{id}` внутри Mini App. Прогресс привязан к этому аккаунту Telegram.", "Mini App ichida `{id}` sifatida kirilgansiz. Progress shu Telegram hisobiga bog'langan.", "Signed in as `{id}` inside the Mini App. Learning state is tied to this Telegram account."),
        "settings.local_personalization": loc("Локальная персонализация", "Mahalliy moslashuv", "Local personalization"),
        "settings.local_personalization_description": loc("Закладки, флаги сложных слов и аудио-предпочтения пока хранятся на этом устройстве.", "Saqlanganlar, qiyin so'z bayroqlari va audio afzalliklari hozircha shu qurilmada saqlanadi.", "Bookmarks, difficult-word flags, and audio preferences are currently stored on this device."),
        "settings.clear_local": loc("Очистить локальные данные", "Mahalliy moslashuvni tozalash", "Clear local personalization"),
        "settings.add_home": loc("Добавить на главный экран", "Bosh ekranga qo'shish", "Add to home screen"),
        "settings.loading": loc("Загрузка настроек", "Sozlamalar yuklanmoqda", "Loading settings"),
        "settings.load_error": loc("Не удалось загрузить настройки.", "Sozlamalarni yuklab bo'lmadi.", "Could not load settings."),
        "settings.save_error": loc("Не удалось сохранить настройки.", "Sozlamalarni saqlab bo'lmadi.", "Could not save settings."),
        "settings.save": loc("Сохранить настройки", "Sozlamalarni saqlash", "Save settings"),
        "progress.loading": loc("Загрузка прогресса", "Progress yuklanmoqda", "Loading progress"),
        "progress.no_data_title": loc("Прогресса пока нет", "Hali progress yo'q", "No progress yet"),
        "progress.no_data_description": loc("Завершите первый урок, и здесь появится статистика.", "Birinchi darsni tugating, shunda statistikalar shu yerda ko'rinadi.", "Complete your first lesson and your learning stats will appear here."),
        "progress.overview": loc("Обзор", "Umumiy ko'rinish", "Overview"),
        "progress.trajectory": loc("Ваша траектория обучения", "Sizning o'rganish trayektoriyangiz", "Your learning trajectory"),
        "progress.trajectory_description": loc("Короткий вид на то, что работает, что проседает и что делать дальше.", "Nima ishlayotgani, nima susaygani va keyin nima qilish kerakligi haqida qisqa ko'rinish.", "A compact view of what is working, what is slipping, and what to do next."),
        "progress.review_health": loc("Здоровье повторения", "Takror holati", "Review health"),
        "progress.load_error": loc("Не удалось загрузить прогресс.", "Progressni yuklab bo'lmadi.", "Could not load progress."),
        "progress.review_health_healthy": loc("Хорошо", "Yaxshi", "Healthy"),
        "progress.review_health_manageable": loc("Под контролем", "Nazorat ostida", "Manageable"),
        "progress.review_health_attention": loc("Нужно внимание", "E'tibor kerak", "Needs attention"),
        "progress.path": loc("Путь", "Yo'l", "Path"),
        "progress.current_path": loc("Текущий путь", "Joriy yo'l", "Current path"),
        "progress.guided_curriculum": loc("Направляемая программа", "Boshqariladigan kurs", "Guided curriculum"),
        "progress.complete_lessons": loc("уроков завершено", "ta dars tugagan", "lessons complete"),
        "progress.current_lesson": loc("Текущий урок", "Joriy dars", "Current lesson"),
        "progress.continue_lesson": loc("Продолжить урок", "Darsni davom ettirish", "Continue lesson"),
        "progress.habit": loc("Ритм", "Ritm", "Habit"),
        "progress.weekly_rhythm": loc("Учёба по неделе", "Haftalik o'qish ritmi", "Weekly study rhythm"),
        "progress.habit_description": loc("В первые месяцы важнее стабильность, а не интенсивность.", "Dastlabki oyларда intensivlikdan ko'ra izchillik muhim.", "Consistency matters more than intensity in the first months."),
        "progress.weak_areas": loc("Слабые места", "Zaif joylar", "Weak areas"),
        "progress.weak_areas_title": loc("Темы, которым нужны дополнительные касания", "Ko'proq qaytishni talab qiladigan mavzular", "Topics that need extra touchpoints"),
        "progress.no_weak_areas": loc("Повторяющихся слабых тем пока нет. Продолжайте наращивать разнообразие.", "Hali takroriy zaif mavzular yo'q. Turfa mashqni davom eting.", "No repeated weak areas yet. Keep building variety."),
        "progress.recommendations": loc("Рекомендации", "Tavsiyalar", "Recommendations"),
        "progress.next": loc("Что делать дальше", "Keyin nima qilish kerak", "What to do next"),
        "progress.clear_due_title": loc("Закрыть просроченные повторы", "Navbatdagi takrorlarni tozalash", "Clear your due reviews"),
        "progress.clear_due_description": loc("В очереди {count} элементов. Короткая сессия улучшит удержание перед следующим уроком.", "{count} ta element kutmoqda. Keyingi darsdan oldin qisqa takror eslab qolishni yaxshilaydi.", "{count} items are waiting. A short review session will improve retention before the next lesson."),
        "progress.repair_title": loc("Исправить недавние ошибки", "Yaqindagi xatolarni tuzatish", "Repair recent mistakes"),
        "progress.repair_description": loc("{count} элементов требуют целевого повтора.", "{count} ta element maqsadli takrorni talab qiladi.", "{count} items need a focused retry."),
        "progress.finish_scenario_title": loc("Завершить активный сценарий", "Faol ssenariyni tugatish", "Finish your active scenario"),
        "progress.finish_scenario_description": loc("Сохраните импульс чтения и аудио сценарием, который уже начали.", "Boshlangan ssenariy bilan o'qish va tinglash ritmini saqlang.", "Keep reading and listening momentum with the scenario you already started."),
        "progress.continue_path_title": loc("Продолжить путь", "Yo'lni davom ettirish", "Continue the guided path"),
        "progress.continue_path_description": loc("Трек уроков готов. Продвиньте следующий урок, пока серия тёплая.", "Dars yo'li tayyor. Seriya issiq ekan, keyingi darsni suring.", "Your lesson track is ready. Push the next lesson forward while your streak is warm."),
    },
    "admin": {
        "section.overview.label": loc("Обзор", "Umumiy ko'rinish", "Overview"),
        "section.overview.description": loc("Метрики и здоровье контента", "Kontent holati va metrikalar", "Health and content metrics"),
        "section.content.label": loc("Контент", "Kontent", "Content"),
        "section.content.description": loc("Сущности и редакторы", "Entitilar va tahrirlash", "Entity managers and editors"),
        "section.queue.label": loc("Очередь публикации", "Nashr navbati", "Publish Queue"),
        "section.queue.description": loc("Черновики, готовые к публикации", "Nashrga tayyor qoralamalar", "Drafts ready for publish"),
        "section.issues.label": loc("Проверка", "Tekshiruv", "Validation"),
        "section.issues.description": loc("Блокирующие ошибки и предупреждения", "Bloklovchi xato va ogohlantirishlar", "Blocking issues and warnings"),
        "section.localization.label": loc("Локализация", "Lokalizatsiya", "Localization"),
        "section.localization.description": loc("Покрытие переводов и пропуски", "Tarjima qamrovi va bo'shliqlar", "Translation coverage and gaps"),
        "section.import_export.label": loc("Импорт / Экспорт", "Import / Eksport", "Import / Export"),
        "section.import_export.description": loc("Пакеты, шаблоны и dry-run", "Paketlar, shablonlar va dry-run", "Packages, templates, and dry-runs"),
        "section.audit.label": loc("Аудит", "Audit", "Audit Trail"),
        "section.audit.description": loc("История изменений и действий", "O'zgarishlar va harakatlar tarixi", "Change history and admin activity"),
        "login.title": loc("Вход администратора", "Admin kirishi", "Admin login"),
        "login.description": loc("Операции с контентом требуют сессии администратора.", "Kontent operatsiyalari uchun admin sessiyasi kerak.", "Content operations require an admin session."),
        "login.email": loc("Почта", "Email", "Email"),
        "login.password": loc("Пароль", "Parol", "Password"),
        "login.submit": loc("Войти", "Kirish", "Login"),
        "workspace.title": loc("Admin CMS", "Admin CMS", "Admin CMS"),
        "workspace.subtitle": loc("Центр управления контентом", "Kontent boshqaruv markazi", "Content control center"),
        "workspace.description": loc("Рабочее пространство для редактирования, публикации, проверки и аудита.", "Tahrir, nashr, tekshiruv va audit uchun ish maydoni.", "Professional workspace for content editing, publish ops, validation, and audit history."),
        "autosave": loc("Автосохранять черновики", "Qoralamalarni avtomatik saqlash", "Autosave drafts"),
        "refresh": loc("Обновить", "Yangilash", "Refresh"),
        "missing.title": loc("Отсутствующие переводы", "Yetishmayotgan tarjimalar", "Missing translations"),
        "missing.description": loc("Эти ключи или языки отсутствуют в опубликованных записях локализации.", "Bu kalitlar yoki tillar chop etilgan lokalizatsiya yozuvlarida yetishmayapti.", "These keys or languages are missing from published localization entries."),
        "missing.empty": loc("Все отслеживаемые ключи сейчас покрыты.", "Hozir kuzatilayotgan barcha kalitlar qoplangan.", "All tracked keys are covered right now."),
        "missing.namespace": loc("Пространство", "Namespace", "Namespace"),
        "missing.key": loc("Ключ", "Kalit", "Key"),
        "missing.language": loc("Язык", "Til", "Language"),
        "missing.open_content": loc("Открыть локализацию", "Lokalizatsiyani ochish", "Open localization"),
    },
}

CATALOG["bot"] = {
    "text.choose_language": loc("Выберите язык интерфейса:", "Interfeys tilini tanlang:", "Choose interface language:"),
    "text.choose_level": loc("Выберите стартовый уровень:", "Boshlang'ich darajani tanlang:", "Choose your starting level:"),
    "text.choose_time": loc("Сколько минут в день удобно заниматься?", "Kuniga necha daqiqa o'qish qulay?", "How many minutes a day feels realistic?"),
    "text.choose_style": loc("Какой формат вам ближе?", "Qaysi usul sizga mos?", "Which learning style fits you best?"),
    "text.onboarded": loc("Маршрут готов. Можно начинать.", "Yo'l tayyor. Boshlash mumkin.", "Your path is ready."),
    "text.settings_saved": loc("Настройки обновлены.", "Sozlamalar yangilandi.", "Settings updated."),
    "text.no_lesson": loc("Сейчас нет доступного урока.", "Hozircha ochiq dars yo'q.", "No lesson is available right now."),
    "text.no_review": loc("Сейчас нет срочного повтора.", "Hozir tezkor takror yo'q.", "No quick review is due right now."),
    "text.no_mistakes": loc("Очередь ошибок пока пуста.", "Xatolar navbati hozircha bo'sh.", "Your mistake queue is empty right now."),
    "text.generic_error": loc("Не удалось загрузить данные. Попробуйте ещё раз.", "Ma'lumotni yuklab bo'lmadi. Yana urinib ko'ring.", "Could not load this right now. Please try again."),
    "text.lesson_heading": loc("Урок", "Dars", "Lesson"),
    "text.lesson_resumed": loc("Продолжаем с текущего шага.", "Joriy bosqichdan davom etamiz.", "Resuming from the current step."),
    "text.lesson_no_resume": loc("Сохранённый шаг недоступен. Открываю актуальный урок.", "Saqlangan bosqich topilmadi. Joriy dars ochiladi.", "The saved step is no longer available. Opening the current lesson."),
    "text.lesson_complete": loc("Урок завершён. Повтор добавлен в очередь.", "Dars tugadi. Takror navbatga qo'shildi.", "Lesson complete. A review item was scheduled."),
    "text.lesson_finished_empty": loc("В уроке пока нет упражнений. Откройте полную версию или перейдите к следующему материалу.", "Bu darsda hozircha mashq yo'q. To'liq ilovani oching yoki keyingi materialga o'ting.", "This lesson has no exercises yet. Open the full app or move to the next material."),
    "text.lesson_prompt_text": loc("Введите ответ по-корейски.", "Javobni koreys tilida yozing.", "Type your answer in Korean."),
    "text.correct": loc("Верно.", "To'g'ri.", "Correct."),
    "text.wrong": loc("Пока нет. Этот пункт вернётся в повторении.", "Hali emas. Bu element keyin takrorlanadi.", "Not quite. This item will come back in review."),
    "text.progress_title": loc("Прогресс", "Progress", "Progress"),
    "text.settings_title": loc("Настройки", "Sozlamalar", "Settings"),
    "button.lesson": loc("Урок", "Dars", "Lesson"),
    "button.review": loc("Повтор", "Takror", "Review"),
    "button.dialogue": loc("Диалог", "Dialog", "Dialogue"),
    "button.library": loc("Библиотека", "Kutubxona", "Library"),
    "button.settings": loc("Настройки", "Sozlamalar", "Settings"),
    "button.menu": loc("Меню", "Menyu", "Menu"),
    "button.app": loc("Mini App", "Mini App", "Mini App"),
    "button.resume": loc("Продолжить", "Davom etish", "Continue"),
    "button.quick_review": loc("Быстрый повтор", "Tezkor takror", "Quick review"),
    "button.mistakes": loc("Ошибки", "Xatolar", "Mistakes"),
    "button.open_app": loc("Открыть Mini App", "Mini App ochish", "Open Mini App"),
    "button.open_lesson": loc("Открыть урок", "Darsni ochish", "Open lesson"),
    "button.open_review": loc("Открыть повтор", "Takrorni ochish", "Open review"),
    "button.open_dialogue": loc("Открыть сценарий", "Ssenariyni ochish", "Open scenario"),
    "button.open_library": loc("Открыть библиотеку", "Kutubxonani ochish", "Open library"),
    "button.open_settings": loc("Открыть настройки", "Sozlamalarni ochish", "Open settings"),
    "button.retry": loc("Повторить", "Qayta urinish", "Retry"),
    "button.knew": loc("Знал", "Bildim", "Knew it"),
    "button.missed": loc("Не вспомнил", "Esga tushmadi", "Missed it"),
    "button.back": loc("Назад", "Orqaga", "Back"),
    "topic.all": loc("Все", "Barchasi", "All"),
    "topic.daily_life": loc("Повседневное", "Kundalik", "Daily life"),
    "topic.food": loc("Еда", "Ovqat", "Food"),
    "topic.shopping": loc("Покупки", "Xarid", "Shopping"),
    "topic.transport": loc("Транспорт", "Transport", "Transport"),
    "topic.study": loc("Учёба", "O'qish", "Study"),
    "topic.work": loc("Работа", "Ish", "Work"),
    "topic.health": loc("Здоровье", "Salomatlik", "Health"),
}


def catalog_entries(namespace: str | None = None) -> dict[str, dict[str, dict[str, str]]]:
    if namespace:
        return {namespace: CATALOG.get(namespace, {})}
    return CATALOG


def catalog_bundle(namespace: str, language: str) -> dict[str, str]:
    entries = CATALOG.get(namespace, {})
    return {key: localized.get(language) or localized.get("en") or key for key, localized in entries.items()}


def catalog_text(namespace: str, key: str, language: str, fallback: str | None = None) -> str:
    localized = CATALOG.get(namespace, {}).get(key)
    if not localized:
        return fallback or key
    return localized.get(language) or localized.get("en") or fallback or key


def sync_catalog_entries(db: Session) -> None:
    for namespace, entries in CATALOG.items():
        for key, localized in entries.items():
            for language in SUPPORTED_LANGUAGES:
                value = str(localized.get(language) or "").strip()
                if not value:
                    continue
                exists = (
                    db.query(LocalizationEntry)
                    .filter(
                        LocalizationEntry.namespace == namespace,
                        LocalizationEntry.key == key,
                        LocalizationEntry.language == language,
                    )
                    .first()
                )
                if exists:
                    continue
                db.add(
                    LocalizationEntry(
                        namespace=namespace,
                        key=key,
                        language=language,
                        value=value,
                        status="published",
                    )
                )
    db.flush()


def iter_catalog_rows(namespace: str | None = None) -> Iterable[tuple[str, str, str]]:
    source = catalog_entries(namespace)
    for current_namespace, entries in source.items():
        for key, localized in entries.items():
            for language in SUPPORTED_LANGUAGES:
                if str(localized.get(language) or "").strip():
                    yield current_namespace, key, language
